apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: improveasin
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - improveasin.space
    secretName: improveasin-space
  rules:
   - host: improveasin.space
     http:
      paths:
      - path: /
        backend:
          serviceName: improveasin
          servicePort: 5000

