name: improveasin

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs: 
  deploy:
     runs-on: ubuntu-latest
    # needs: [build]
    
     steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Shell
        run: |
          pwd
          sed -i "s/<VERSION>/${{ github.sha }}/g" deployment/manifests/deployment.yml
         
      - name: Set kubernetes secrets
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: k8s deployment
        run: |
           kubectl apply -f deployment/manifests/api-ingress.yml
           kubectl apply -f deployment/manifests/deployment.yml
           kubectl apply -f deployment/manifests/service.yml
